### ISSUE TITLE
HawkEye Web-Interface

### ISSUE THREAD

**Issue by AgentOak** [pp3345/Pancake#1]
http://hawk.craftination.de/

<pre>Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /usr/local/Pancake/sys/php/sapi.php on line 285 MySQL server has gone away</pre>

Caused by the following code:

``` php
<?php

        function error($msg) {
                die($msg);
        }

        session_start();

        //Include config and lang pack
        include("config.php");
        include("langs/" . $hawkConfig["langFile"]);
```

Pancake 1.0, tested with PHP 5.4.7-dotdeb and self-compiled PHP 5.4.7RC1

**Comment by pp3345** [comment]
Fixed in commit 5ff8deb4b70a1c19acd79dafd1c7e062292c1069.
