### ISSUE TITLE
Can't use method return value in write context

### ISSUE THREAD

**Issue by ghost** [pp3345/Pancake#2]
$ sudo ./pancake.sh
Found x86_64 processor
Found PHP 5.3
[Master]  Loading Pancake 1.2-devel... 2012 Yussuf Khalil
PHP Fatal error:  Can't use method return value in write context in /home/sam/Pancake/sys/threads/single/requestWorker.thread.cphp on line 726
[Master] 25.11.12 20:21:41 Failed to boot RequestWorker #1 in time - Aborting
[Master] 25.11.12 20:21:41 Stopping...
[Master] 25.11.12 20:21:41 Waiting for PHPWorker #1 ("default") to stop
[Master] 25.11.12 20:21:41 Waiting for PHPWorker #2 ("default") to stop
[Master] 25.11.12 20:21:41 Waiting for PHPWorker #3 ("default") to stop

$ php -v
PHP 5.3.10-1ubuntu3.4 with Suhosin-Patch (cli) (built: Sep 12 2012 18:59:41) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

$ php -m | grep "pcntl|sysvmsg|sockets"
pcntl
sockets
sysvmsg

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.1 LTS
Release:    12.04
Codename:   precise

$ whoami
sam

**Comment by pp3345** [comment]
Fixed in https://github.com/pp3345/Pancake/commit/63b3171b4d3e0a843cf2381d2ac0f320f78145fb. I had accidently commited some debug code.

**Comment by ghost** [comment]
Same deal as above but..

PHP Parse error:  syntax error, unexpected '{' in /home/sam/Pancake/sys/threads/single/requestWorker.thread.cphp on line 800
[Master] 25.11.12 20:56:29 Failed to boot RequestWorker #1 in time - Aborting
[Master] 25.11.12 20:56:29 Stopping...
[Master] 25.11.12 20:56:29 Waiting for PHPWorker #1 ("default") to stop
[Master] 25.11.12 20:56:29 Waiting for PHPWorker #2 ("default") to stop
[Master] 25.11.12 20:56:29 Waiting for PHPWorker #3 ("default") to stop

**Comment by pp3345** [comment]
Fixed in https://github.com/pp3345/Pancake/commit/a43a223bb177b561a0e0dcf76178516043362ecf. I made a quick commit some minutes ago, did not test the code and therefore did not realize there was a ")" missing.

**Comment by ghost** [comment]
No problem.
